// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wanetra.Infrastructure.Persistence;

#nullable disable

namespace Wanetra.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WanetraDbContext))]
    [Migration("20260921101252_AddAlertState")]
    partial class AddAlertState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Wanetra.Domain.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailuresRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveRecoveriesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DownloadBaselineDropPercent")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxJitterMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxPacketLossPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinDownloadMbps")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinUploadMbps")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("UploadBaselineDropPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("Wanetra.Domain.AlertState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveHealthyMeasurements")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveUnhealthyMeasurements")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RuleUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlertStates");
                });

            modelBuilder.Entity("Wanetra.Domain.DegradationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BaselineDownloadMbps")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaselineUploadMbps")
                        .HasColumnType("REAL");

                    b.Property<int>("ConsecutiveHealthyMeasurements")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveUnhealthyMeasurements")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxJitterMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxPacketLossPercent")
                        .HasColumnType("REAL");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecoveryNotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("WorstDownloadMbps")
                        .HasColumnType("REAL");

                    b.Property<double?>("WorstUploadMbps")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("DegradationEvents");
                });

            modelBuilder.Entity("Wanetra.Domain.NotificationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.ToTable("NotificationConfigurations");
                });

            modelBuilder.Entity("Wanetra.Domain.ScheduleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduleSettings");
                });

            modelBuilder.Entity("Wanetra.Domain.SpeedTestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DownloadMbps")
                        .HasColumnType("REAL");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Isp")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double?>("JitterMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("PacketLossPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("ServerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerLocation")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("UploadMbps")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SpeedTestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
